/**
 * Krak REST API
 * Krak REST API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Boreholes from './model/Boreholes';
import CorePhotos from './model/CorePhotos';
import CorePhotosData from './model/CorePhotosData';
import BoreholesApi from './api/BoreholesApi';
import CorePhotosApi from './api/CorePhotosApi';


/**
* Krak_REST_API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var KrakRestApi = require('index'); // See note below*.
* var xxxSvc = new KrakRestApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new KrakRestApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new KrakRestApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new KrakRestApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Boreholes model constructor.
     * @property {module:model/Boreholes}
     */
    Boreholes,

    /**
     * The CorePhotos model constructor.
     * @property {module:model/CorePhotos}
     */
    CorePhotos,

    /**
     * The CorePhotosData model constructor.
     * @property {module:model/CorePhotosData}
     */
    CorePhotosData,

    /**
    * The BoreholesApi service constructor.
    * @property {module:api/BoreholesApi}
    */
    BoreholesApi,

    /**
    * The CorePhotosApi service constructor.
    * @property {module:api/CorePhotosApi}
    */
    CorePhotosApi
};
