/**
 * Krak REST API
 * Krak REST API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Boreholes model module.
 * @module model/Boreholes
 * @version 0.0.1
 */
class Boreholes {
    /**
     * Constructs a new <code>Boreholes</code>.
     * @alias module:model/Boreholes
     * @param name {String} Name of the borehole
     * @param easting {Number} Easting position of the collar
     * @param northing {Number} Northing position of the collar
     * @param elevation {Number} Elevation position of the collar
     */
    constructor(name, easting, northing, elevation) { 
        
        Boreholes.initialize(this, name, easting, northing, elevation);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, easting, northing, elevation) { 
        obj['name'] = name;
        obj['easting'] = easting;
        obj['northing'] = northing;
        obj['elevation'] = elevation;
    }

    /**
     * Constructs a <code>Boreholes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Boreholes} obj Optional instance to populate.
     * @return {module:model/Boreholes} The populated <code>Boreholes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Boreholes();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('easting')) {
                obj['easting'] = ApiClient.convertToType(data['easting'], 'Number');
            }
            if (data.hasOwnProperty('northing')) {
                obj['northing'] = ApiClient.convertToType(data['northing'], 'Number');
            }
            if (data.hasOwnProperty('elevation')) {
                obj['elevation'] = ApiClient.convertToType(data['elevation'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Name of the borehole
 * @member {String} name
 */
Boreholes.prototype['name'] = undefined;

/**
 * Easting position of the collar
 * @member {Number} easting
 */
Boreholes.prototype['easting'] = undefined;

/**
 * Northing position of the collar
 * @member {Number} northing
 */
Boreholes.prototype['northing'] = undefined;

/**
 * Elevation position of the collar
 * @member {Number} elevation
 */
Boreholes.prototype['elevation'] = undefined;






export default Boreholes;

