/**
 * Krak REST API
 * Krak REST API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CorePhotosData model module.
 * @module model/CorePhotosData
 * @version 0.0.1
 */
class CorePhotosData {
    /**
     * Constructs a new <code>CorePhotosData</code>.
     * @alias module:model/CorePhotosData
     * @param depthFrom {Number} 
     * @param depthTo {Number} 
     */
    constructor(depthFrom, depthTo) { 
        
        CorePhotosData.initialize(this, depthFrom, depthTo);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, depthFrom, depthTo) { 
        obj['depth_from'] = depthFrom;
        obj['depth_to'] = depthTo;
    }

    /**
     * Constructs a <code>CorePhotosData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CorePhotosData} obj Optional instance to populate.
     * @return {module:model/CorePhotosData} The populated <code>CorePhotosData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CorePhotosData();

            if (data.hasOwnProperty('depth_from')) {
                obj['depth_from'] = ApiClient.convertToType(data['depth_from'], 'Number');
            }
            if (data.hasOwnProperty('depth_to')) {
                obj['depth_to'] = ApiClient.convertToType(data['depth_to'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} depth_from
 */
CorePhotosData.prototype['depth_from'] = undefined;

/**
 * @member {Number} depth_to
 */
CorePhotosData.prototype['depth_to'] = undefined;






export default CorePhotosData;

