/**
 * Krak REST API
 * Krak REST API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KrakRestApi);
  }
}(this, function(expect, KrakRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KrakRestApi.BoreholesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BoreholesApi', function() {
    describe('boreholesCreate', function() {
      it('should call boreholesCreate successfully', function(done) {
        //uncomment below and update the code to test boreholesCreate
        //instance.boreholesCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('boreholesDelete', function() {
      it('should call boreholesDelete successfully', function(done) {
        //uncomment below and update the code to test boreholesDelete
        //instance.boreholesDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('boreholesReadAll', function() {
      it('should call boreholesReadAll successfully', function(done) {
        //uncomment below and update the code to test boreholesReadAll
        //instance.boreholesReadAll(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('boreholesReadOne', function() {
      it('should call boreholesReadOne successfully', function(done) {
        //uncomment below and update the code to test boreholesReadOne
        //instance.boreholesReadOne(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('boreholesUpdate', function() {
      it('should call boreholesUpdate successfully', function(done) {
        //uncomment below and update the code to test boreholesUpdate
        //instance.boreholesUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
